config/routes.rb
Rails.application.routes.draw do
  get 'tags/create'
  get 'tags/destroy'

  root 'top#index'
  get 'about' => 'top#about', :as => :about
  get 'top/index'
  resources :users do
    resources :tasks do
      collection do
        get :download
      end
      controller :tags do
        post 'create' => 'tags#create', as: 'tags_create'
        post 'destroy' => 'tags#destroy', as: 'tags_destroy'
      end
    end
  end
  get 'logout' => 'session#destroy'
  get 'login' => 'session#new'
  resource :session, only: 'create', controller: 'session'

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :task_tags
  has_many :tasks, through: :task_tags
  validates :name, presence: true, uniqueness: true
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user
  has_many :task_tags
  has_many :tags, through: :task_tags
  validates :name, presence: true, uniqueness: true
  validates :deadline, presence: true
  validates :priority, inclusion: { in: 1..3 }
  scope :near_deadline, lambda{ where('deadline < ?', 1.days.since) }
  scope :high, lambda{ where(priority: 3) }
  scope :by_name, lambda{|name|
    where(:name => name) if name.present?}
  scope :like_name, lambda{ |name| where("name like ?", "%#{name}%") if name.present? }
end

app/models/task_tag.rb
class TaskTag < ActiveRecord::Base
  belongs_to :task
  belongs_to :tag
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :tasks
  validates :name,
            presence: true,
            uniqueness: { case_sensitive: false }
  validates :password,
            presence: true,
            confirmation: true
  before_save :digest_password

  def self.authenticate(email, password)
    where(email: email, password: Digest::SHA1.hexdigest(password)).first
  end

  private

  def digest_password
    self.password = Digest::SHA1.hexdigest(self.password)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :find_login_user

  def find_login_user
    @login_user = User.find_by_id(session[:user_id])
    unless @login_user
      redirect_to login_url and return false
    end
  end

  private

  def admin_required
    unless @login_user.adm?
      redirect_to user_path(@login_user)
    end
  end
end

app/controllers/session_controller.rb
# coding: utf-8
class SessionController < ApplicationController
  skip_before_filter :find_login_user, only: [:new, :create]
  def new
  end

  def create
    @email = params[:email]
    @password = params[:password]
    @user = User.authenticate(@email, @password)
    session[:user_id] = @user.try(:id)
    if @user.nil?
      flash.now[:alert] = 'Login failed!'
      render action: :new
    elsif @user.try(:adm?)
      flash[:notice] = 'Login success!'
      redirect_to users_path
    else
      redirect_to user_path(@user)
    end
  end

  def destroy
    reset_session
    redirect_to root_url
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :retrieve_user
  before_action :find_task

  def create
    unless params[:name].blank?
      tag = Tag.where(name: params[:name]).first ||
            Tag.create(name: params[:name])
      @task.tags << tag unless @task.tags.where(id: tag.id).first
    end
    redirect_to user_task_path(@user, @task)
  end

  def destroy
    if tag = Tag.where(name: params[:name]).first
      @task.tags.delete(tag)
    end
    redirect_to user_task_path(@user, @task)
  end

  def find_task
    @task = @user.tasks.find(params[:task_id])
  end

  def retrieve_user
    unless @user = User.where(id: params[:user_id]).first and
           (@login_user.adm? or @login_user.id == @user.id)
      redirect_to user_path(@login_user)
    end
  end
end

app/controllers/tasks_controller.rb
require 'csv'
class TasksController < ApplicationController
  before_action :retrieve_user
  before_action :find_task, only: [:show, :edit, :update, :destroy]

  def index
    @name = params[:name]
    @tasks = @user.tasks.like_name(@name).all
    unless params[:tag].blank?
      @tasks = @tasks.includes(:tags).where(tags: { name: params[:tag] })
    end
  end

  def new
    @task = @user.tasks.new
  end

  def edit
  end

  def show
  end

  def create
    @task = @user.tasks.new(task_params)

    if @task.save
      redirect_to user_tasks_url(@user), notice: 'Task was successfully created.'
    else
      render action: :new
    end
  end

  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to user_tasks_url(@user), notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @task.destroy
    redirect_to user_tasks_url(@user)
  end

  def download
    @tasks = @user.tasks
    csvs = CSV.generate do |csv|
      @tasks.each do |task|
        csv << [task.name, task.deadline.strftime("%Y-%m-%d %H:%M:%S"), task.priority]
      end
    end
    send_data csvs, :type => 'text/csv', :filename => 'tasks.csv'
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def task_params
    params.require(:task).permit(:name, :deadline, :priority)
  end

  def retrieve_user
    unless @user = User.where(id: params[:user_id]).first and
           (@login_user.adm? or @login_user.id == @user.id)
      redirect_to user_path(@login_user)
    end
  end

  def find_task
    @task = @user.tasks.find(params[:id])
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  skip_before_filter :find_login_user, only: [:about]
  def index
    render action: :about
  end
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :find_login_user, :only => [:new, :create]
  before_action :set_user, :only => [:show, :edit, :update, :destroy]
  before_action :admin_required, :only => [:index, :destroy]
  before_action :user_allow_show_own_data, :only => [:show, :edit, :update]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
    respond_to do |format|
      format.html
      format.xml { render :xml => @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to login_path, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: login_path }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :birthday, :password)
    end

    def user_allow_show_own_data
      unless @login_user.try(:adm?) or @login_user.id == @user.id
        redirect_to user_path(@login_user)
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/tasks_helper.rb
# coding: utf-8
module TasksHelper
  def priority_name(priority)
    { 1 => 'Low', 2 => 'Middle', 3 => 'High' }[priority]
  end
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Todo" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>
    <%= render "shared/header" %>

    <div class="container">
      <div class="row">
        <%= bootstrap_flash %>
        <%= yield %>
      </div><!--/row-->
    </div> <!-- /container -->

  </body>
</html>

app/views/session/new.html.erb
<div class="container">
  <div class="row">
    <div class="span12">
      <div class="" id="loginModal">
        <div class="modal-header">
          <h3>Have an Account?</h3>
        </div>
        <div class="modal-body">
          <div class="well">
            <ul class="nav nav-tabs">
              <li class="active"><a href="#login" data-toggle="tab">Login</a></li>
              <li><a href="#create" data-toggle="tab">Create Account</a></li>
            </ul>
            <div id="myTabContent" class="tab-content" style='padding:20px 0 0 0'>
              <div class="tab-pane active in" id="login">
                <%= form_tag(session_url, class: 'form-horizontal') do %>
                  <fieldset>
                    <div class="form-group">
                      <div class="col-sm-4">
                        <%= text_field @email, :email, class: 'form-control', placeholder: 'Email' %>
                      </div>
                    </div>
                    <div class="form-group">
                      <div class="col-sm-4">
                        <%= password_field_tag :password, "", class: 'form-control', placeholder: 'Password' %>
                      </div>
                    </div>
                    <div>
                      <%= submit_tag 'Login', class: 'btn btn-success' %>
                    </div>
                  </fieldset>
                <% end %>
              </div>

              <div class="tab-pane fade" id="create">
                <%= form_for User.new, :html => {:class => "form-horizontal"} do |f| %>
                  <div class="form-group">
                    <%= f.label :name, '', class: 'control-label col-sm-1' %>
                    <div class="col-sm-4">
                      <%= f.text_field :name, class: 'form-control', placeholder: 'Enter Name' %>
                    </div>
                  </div>
                  <div class="form-group">
                    <%= f.label :Email, '', class: 'control-label col-sm-1' %>
                    <div class="col-sm-4">
                      <%= f.text_field :email, class: 'form-control', placeholder: 'Enter Email' %>
                    </div>
                  </div>
                  <div class="form-group">
                    <%= f.label :Birthday, '', class: 'control-label col-sm-1' %>
                    <div class="col-sm-4">
                      <%= f.text_field :birthday, class: 'form-control', placeholder: 'YYYY/MM/DD' %>
                    </div>
                  </div>
                  <div class="form-group">
                    <%= f.label :Password, '', class: 'control-label col-sm-1' %>
                    <div class="col-sm-4">
                      <%= f.password_field :password, class: 'form-control', placeholder: 'Password' %>
                    </div>
                  </div>
                  <div class="form-group">
                    <div class="col-sm-1"></div>
                    <div class="col-sm-4">
                      <%= f.password_field :password_confirmation, class: 'form-control', placeholder: 'Password_confirmation' %>
                    </div>
                  </div>
                  <div class="col-sm-1"></div>
                  <div>
                    <%= f.submit 'Create Account', class: 'btn btn-primary' %>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_header.html.erb
<div id="head" class="navbar navbar-default navbar-static-top navbar-fixed-top">
  <div class="container">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to 'ToDo', :root, class: 'navbar-brand' %>
    <div class="navbar-collapse collapse navbar-responsive-collapse">
      <% if @login_user %> 
        <ul class="nav navbar-nav">
          <li><%= link_to 'TaskList', user_tasks_path(@login_user) %></li>
          <li>
            <%= form_tag user_tasks_path(@login_user), class: 'navbar-form', method: :get do %>
              <%= text_field_tag('name', @name, class: 'form-control', placeholder: 'Search task' ) %>
            <% end %>
          </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to @login_user.email, :users %></li>
          <li><%= link_to 'Logout', :logout %></li>
        </ul>
      <% elsif @login_user.blank? %>
        <ul class="nav navbar-nav">
          <li><%= link_to 'About', :about %></li>
        </ul>
      <% end %> 
    </div>
  </div>
</div>

app/views/tags/create.html.erb
<h1>Tags#create</h1>
<p>Find me in app/views/tags/create.html.erb</p>

app/views/tags/destroy.html.erb
<h1>Tags#destroy</h1>
<p>Find me in app/views/tags/destroy.html.erb</p>

app/views/tasks/_form.html.erb
<%= form_for [@user, @task], :html => { :class => "form-horizontal task" } do |f| %>
  <div class="container">
    <% if @task.errors.any? %>
      <div id="error_expl" class="panel panel-danger">
        <div class="panel-heading">
          <h3 class="panel-title"><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h3>
        </div>
        <div class="panel-body">
          <ul>
            <% @task.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      </div>
    <% end %>

    <div class="row">
      <div class="col-xs-4">
        <div class="form-group">
          <%= f.label :name, class: 'control-label' %>
          <%= f.text_field :name, class: 'form-control', placeholder: 'Enter  the Task Name' %>
          <%= error_span(@task[:name]) %>
        </div>
        <div class="form-group">
          <%= f.label :deadline, class: 'control-label' %>
          <%= f.text_field :deadline, class: 'form-control', placeholder: 'YYYY/MM/DD' %>
          <%= error_span(@task[:deadline]) %>
        </div>
        <div class="form-group">
          <label class="control-label">Priority</label><br />
          <label class="radio-inline">
            <%= f.radio_button 'priority', 1 %>
            Low
          </label>
          <label class="radio-inline">
            <%= f.radio_button 'priority', 2 %>
            Middle
          </label>
          <label class="radio-inline">
            <%= f.radio_button 'priority', 3 %>
            High
          </label>
        </div>
        <%= error_span(@task[:priority]) %>
      </div>
    </div>
  </div>
  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
        user_tasks_path(@user), :class => 'btn btn-default' %>
<% end %>

app/views/tasks/edit.html.erb
<%- model_class = Task -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/tasks/index.html.erb
<%- model_class = Task -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:deadline) %></th>
      <th><%= model_class.human_attribute_name(:priority) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%= model_class.human_attribute_name(:tag) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= link_to(task.name, user_task_path(@user, task)) %></td>
        <td><%= task.deadline %></td>
        <td><%= priority_name(task.priority) %></td>
        <td><%= task.created_at %></td>
        <td><%= task.tags.all.map{|tag| link_to(tag.name, user_tasks_path(@user, tag: tag.name))}.join(", ").html_safe -%></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_user_task_path(@user, task), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      user_task_path(@user, task),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_user_task_path(@user),
            :class => 'btn btn-primary' %>

<%= link_to 'Download_List', download_user_tasks_path(@user), class: 'btn btn-success' %>

app/views/tasks/new.html.erb
<%- model_class = Task -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/tasks/show.html.erb
<%- model_class = Task -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @task.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:deadline) %>:</strong></dt>
  <dd><%= @task.deadline %></dd>
  <dt><strong><%= model_class.human_attribute_name(:priority) %>:</strong></dt>
  <dd><%= priority_name(@task.priority) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:tag) %>:</strong></dt>
  <dd>
    <table>
      <% @task.tags.each do |tag| %>
        <tr>
          <td><%= form_tag(user_task_tags_destroy_path(@user, @task)) do %>
              <%= hidden_field_tag :name, tag.name %>
              <%= link_to(tag.name, user_tasks_path(@user, tag: tag.name)) %>
              <%= submit_tag '削除' %>
            <% end %>
          </td>
        </tr>
      <% end %>
      <tr>
        <td>
          <%= form_tag(user_task_tags_create_path(@user, @task)) do %>
            <%= text_field_tag :name %>
            <%= submit_tag "追加" %>
          <% end %>
        </td>
      </tr>
    </table>
  </dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              user_tasks_path(@user), :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_user_task_path(@user, @task), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              user_task_path(@user, @task),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/top/about.html.erb
<div class="container">
<p>This is a Task Management Application</p>
</div>

app/views/users/_form.html.erb
<%= form_for @user, :html => { :class => "form-horizontal user" } do |f| %>

  <% if @user.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
          <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="row col">
    <div class="col-xs-4">
      <div class="control-group">
        <%= f.label :name, :class => 'control-label' %>
        <div class="controls">
          <%= f.text_field :name, :class => 'form-control' %>
        </div>
        <%= error_span(@user[:name]) %>
      </div>
      <div class="control-group">
        <%= f.label :email, :class => 'control-label' %>
        <div class="controls">
          <%= f.text_field :email, :class => 'form-control' %>
        </div>
        <%= error_span(@user[:email]) %>
      </div>
      <div class="control-group">
        <%= f.label :birthday, :class => 'control-label' %>
        <div class="controls">
          <%= f.text_field :birthday, :class => 'form-control' %>
        </div>
        <%= error_span(@user[:birthday]) %>
      </div>

      <% if ["new", "create", "edit", "update"].include?(action_name) %>
        <div class="control-group">
          <%= f.label :password, :class => 'control-label' %>
          <div class="controls">
            <%= f.password_field :password, :class => 'form-control' %>
          </div>
          <%= error_span(@user[:password]) %>
        </div>
        <div class="control-group">
          <%= f.label :password_confirmation, :class => 'control-label' %>
          <div class="controls">
            <%= f.password_field :password_confirmation, :class => 'form-control' %>
          </div>
          <%= error_span(@user[:password_confirmation]) %>
        </div>
      <% end %>

      <% if @login_user.try(:adm?) %>
        <div class="control-group">
          <%= f.label :adm, :class => 'control-label' %>
          <div class="controls">
            <%= f.text_field :adm, :class => 'form-control' %>
          </div>
          <%= error_span(@user[:adm]) %>
        </div>
      <% end %>
    </div>
  </div>

  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            users_path, :class => 'btn btn-default' %>
<% end %>

app/views/users/edit.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/index.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:birthday) %></th>
      <th><%= model_class.human_attribute_name(:password) %></th>
      <th><%= model_class.human_attribute_name(:adm) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.id, user_path(user) %></td>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.birthday %></td>
        <td><%= user.password %></td>
        <td><%= user.adm %></td>
        <td><%= user.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_user_path(user), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      user_path(user),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_user_path,
            :class => 'btn btn-primary' %>

app/views/users/new.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/show.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @user.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @user.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:birthday) %>:</strong></dt>
  <dd><%= @user.birthday %></dd>
</dl>

<% if @login_user.try(:adm?) %> 
  <%= link_to t('.back', :default => t("helpers.links.back")),
                users_path, :class => 'btn btn-default'  %>
<% end %> 
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_user_path(@user), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              user_path(@user),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>